#!/bin/bash
#
# GamePanelX
# Remote scripts v3.0.11
#
# Queue a password change of a gpx user account
# -p passwords should be done with crypt() before giving it here, no plaintext passwords can be used here.
# Example usage:
#
# ./ChangePassword -u test1 -p pass123
#
sso_user=
sso_pass=
tmp_dir="$HOME/tmp"
queue_dir="$HOME/queue"
rand_str="$(date +%s | sha256sum | base64 | head -c 24 ; echo)"

while getopts "u:p:" OPTION
do
     case $OPTION in
         u)
             sso_user=$OPTARG
             ;;
         p)
             sso_pass=$OPTARG
             ;;
         ?)
             exit
             ;;
     esac
done

# Check empty
if [[ "$sso_user" == "" || "$sso_pass" == "" ]]
then
	echo "Insufficient info given, exiting."
	exit
fi

# No system accounts in local mode.  Just exit

echo "success"
