#!/bin/bash
#
# GamePanelX
# Remote scripts v3.0.12
#
# Check status of Template creation
#

#
# Example usage:
# ./CheckTemplateStatus -i fa4990f190de97a37abfab9980e8df8e06bbc291
#
tpl_hash=

while getopts "i:" OPTION
do
     case $OPTION in
         i)
             tpl_hash=$OPTARG
             ;;
         ?)
             exit
             ;;
     esac
done

if [[ "$tpl_hash" == "" ]]
then
  echo "CheckTemplateStatus: Required settings were left out.  Exiting."
  exit
fi

if [ -f $HOME/templates/.gpx_$tpl_hash ]
then
    pid=`cat $HOME/templates/.gpx_$tpl_hash`
    check_pid=`ps aux | grep $pid | grep -v grep`

    if [ "$check_pid" == "" ]
    then
      echo "complete"
    else
      echo "running"
    fi
else
    echo "complete"
fi
