#!/bin/bash
#
# GamePanelX
# Remote scripts v3.0.12
#
# Get contents of a file
#
# Example usage:
# ./FileContent -f /path/to/some/file.txt
#
file=

while getopts "f:" OPTION
do
     case $OPTION in
         f)
             file=$OPTARG
             ;;
         ?)
             exit
             ;;
     esac
done

if [ "$file" == "" ]
then
  echo "FileContent: No filename given! Exiting."
  exit
fi

cat $file
